import type { Metadata } from "next";
import { DoctorProfileClientChrome } from "./DoctorProfileClientChrome";
import { SITE_NAME, SITE_URL } from "@/lib/site-data";

/* ------------------------------------------------------------------
   Doctor profile — Dr. Md. Miftah Ur Rahman (/doctors/dr-miftah-ur-rahman).

   Self-referencing canonical (NOT canonicalised to /about — the About
   page's legacy block links here now, not the other way round).
   og:type is "profile" and the og:image is the doctor-specific
   1200x630 crop generated by scripts/derive-og-miftah.mjs, which is
   deliberately different from the sitewide OG image.
   ------------------------------------------------------------------ */

const title = `Dr. Md. Miftah Ur Rahman | Prosthodontist & Implantologist Hyderabad`;
const description =
  "Dr. Md. Miftah Ur Rahman, BDS, MDS, FICOI — Prosthodontist and Implantologist at Neodent Dental Hospital, Mehdipatnam and Nampally, Hyderabad. Assistant Professor of Prosthodontics.";
const path = "/doctors/dr-miftah-ur-rahman";
const url = `${SITE_URL}${path}`;

/* og:image — the doctor's own 1200x630 portrait crop, face-centred.
   Different from the sitewide OG image by design. */
const ogImage = "/assets/dr-miftah/og-dr-miftah-ur-rahman-1200x630.jpg";

/* Portrait referenced by the Person entity — encode spaces for the
   absolute URL form schema.org/Google prefer. */
const portraitUrl = `${SITE_URL}/assets/dr-miftah/${encodeURIComponent("Dr Md Miftah at Dept of Prosthodontics at SB Patil Dental College.jpeg")}`;

export const metadata: Metadata = {
  title: { absolute: title },
  description,
  alternates: {
    canonical: path,
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title,
    description,
    url: path,
    siteName: SITE_NAME,
    locale: "en_IN",
    type: "profile",
    images: [
      {
        url: ogImage,
        width: 1200,
        height: 630,
        alt: "Dr. Md. Miftah Ur Rahman at the Department of Prosthodontics, SB Patil Dental College & Hospital",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    images: [ogImage],
  },
};

/**
 * Page-level JSON-LD: ProfilePage wrapping a Person, plus a
 * BreadcrumbList. Every value here matches text visible on the page.
 * Deliberately NO Review / AggregateRating / FAQPage /
 * MedicalProcedure schema (see also the patient-voices section copy,
 * which carries no structured data).
 *
 * Deliberately NO dateModified either. This project has no per-page
 * content timestamp to draw from -- no CMS, API or database (the same
 * note appears in app/sitemap.ts). dateModified is only *recommended*
 * on ProfilePage; Google requires just mainEntity, so omitting it
 * cannot raise a structured-data error. It claims nothing rather than
 * inventing a build-time date.
 *
 * This replaces `new Date().toISOString().split("T")[0]`, whose
 * date-only "YYYY-MM-DD" output Search Console's strict validator
 * rejects: "Invalid datetime value" -- a datetime is expected to carry
 * a time. If a real modification timestamp is ever tracked, emit a
 * FULL ISO 8601 datetime including a time and a timezone offset, e.g.
 * "2026-09-21T23:09:33+05:30". scripts/verify-jsonld.mjs enforces that
 * shape and fails on any date-only value.
 */
const doctorJsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    "@id": `${url}/#profilepage`,
    url,
    mainEntity: {
      "@type": ["Person", "Physician"],
      "@id": `${url}/#person`,
      name: "Dr. Md. Miftah Ur Rahman",
      jobTitle: "Prosthodontist & Implantologist",
      image: portraitUrl,
      url,
      worksFor: { "@id": `${SITE_URL}/#organization` },
      affiliation: "SB Patil Dental College & Hospital",
      /* "Dentistry" is the actual schema.org MedicalSpecialty enum value;
         "Prosthodontics"/"Implantology" are not enum values, so they stay
         as free text in knowsAbout. */
      medicalSpecialty: "Dentistry",
      knowsAbout: [
        "Prosthodontics",
        "Implantology",
        "Dental Implants",
        "Full Mouth Rehabilitation",
        "Smile Design",
      ],
      alumniOf: "Sri Sai College of Dental Surgery",
    },
  },
  {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "@id": `${url}/#breadcrumb`,
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: SITE_URL,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Doctors",
        item: `${SITE_URL}/doctors`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: "Dr. Md. Miftah Ur Rahman",
        item: url,
      },
    ],
  },
];

export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(doctorJsonLd) }}
      />
      <DoctorProfileClientChrome />
    </>
  );
}
